WebFileManager/Controllers/FilesControllers/FilesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebFileManager.Models;
using WebFileManager.Models.FilesModels;
using System.IO;


namespace WebFileManager.Controllers
{
    public class FilesController : Controller
    {
        /// <summary>
        /// сразу в память чтоб не пересчитывать каждый раз размер
        /// </summary>
        public static DisksModel disk = new DisksModel();
        public static List<FolderModel> folderModels = FolderModel.GetFolderModels();
        [HttpGet]
        public IActionResult Files()
        {
            return View("~/Views/FilesViews/Files.cshtml");
        }
        /// <summary>
        /// отправляет представление папки по указанному пути
        /// </summary>
        /// <param name="folderName">путь к папке(сейчас или полный)</param>
        /// <param name="pathNow">(необязательный)добавляет к folderName следующую папку</param>
        /// <param name="orderBy">сортировка по полю</param>
        /// <param name="back">true-возвращает на папку назад от folderName</param>
        /// <returns></returns>
        [HttpPost]
        public ContentResult NewFolder(string folderName, string pathNow, string orderBy=null, bool back=false)
        {
            if (orderBy != null)
            {
                if (HttpContext.Session.GetString("OrderBy") == orderBy)
                {
                    if (HttpContext.Session.GetString("SortType") == "Asc") { HttpContext.Session.SetString("SortType", "Desc"); }
                    else { HttpContext.Session.SetString("SortType", "Asc"); }
                }
                else
                {
                    HttpContext.Session.SetString("OrderBy", orderBy);
                    HttpContext.Session.SetString("SortType", "Asc");
                }
            }
            return Content(folderModels.GetFolderViewModel(!back ? pathNow: pathNow.Substring(0, pathNow.LastIndexOf("\\")), folderName, HttpContext.Session.GetString("OrderBy"), HttpContext.Session.GetString("SortType")).ToJson(), "application/json");
        }
        [HttpPost]
        public ContentResult NewFolderNext(string pathNow)
        {
            if (HttpContext.Session.GetString("maxPath") != pathNow && pathNow.Contains(HttpContext.Session.GetString("maxPath")))
            {
                if (HttpContext.Session.GetString("SortType") == "Asc") { HttpContext.Session.SetString("SortType", "Desc"); }
                else { HttpContext.Session.SetString("SortType", "Asc"); }
                return Content(folderModels.GetFolderViewModel(pathNow.Substring(0, pathNow.LastIndexOf("\\")), null, HttpContext.Session.GetString("OrderBy"), HttpContext.Session.GetString("SortType")).ToJson(), "application/json");
            }
            return null;
        }
    }
}

WebFileManager/Controllers/SessionsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace WebFileManager.Controllers
{
    public class SessionsController : Controller
    {

        [HttpPost]
        public ContentResult GetSessionValueByName(string name)
        {
            
            if (HttpContext.Session.Keys.Contains(name))
            {
                var a = HttpContext.Session.GetString(name);
                return Content(HttpContext.Session.GetString(name));
            }
            else
            {
                return Content(null);
            }
        }
        [HttpPost]
        public void SetSessionValue(string name, string value)
        {
            HttpContext.Session.SetString(name, value);
        }

    }
}

WebFileManager/Views/FilesViews/Files.cshtml
@using WebFileManager.Models.FilesModels;
@using System.IO;
@{
    ViewData["Title"] = "Files";
}

<div id="diskInfo">
    <div id="tableDisk">
        <table onclick="VieUnvie()" style="cursor: pointer">
            <tr>
                <td>
                    <img src="~/img/hd_disk_harddisk_162.png" style="height:45px;width:45px" />
                </td>
                <td>
                    <table>
                        <tr>
                            <td>
                                Все пространство дисков
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <progress value="@(WebFileManager.Controllers.FilesController.disk.TotalSize.ToGB(0) - WebFileManager.Controllers.FilesController.disk.TotalFreeSpace.ToGB(0))" max="@WebFileManager.Controllers.FilesController.disk.TotalSize.ToGB(0)"></progress>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @WebFileManager.Controllers.FilesController.disk.TotalFreeSpace.ToGB() ГБ свободно из @WebFileManager.Controllers.FilesController.disk.TotalSize.ToGB() ГБ
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <table id="allDisk" style="display:none; cursor: pointer">
            @{foreach (DriveInfo driveInfo in WebFileManager.Controllers.FilesController.disk.Disks)
                {
                    <tr class="DiskRow" onclick="getFolder(null,'@(driveInfo.Name+"\\")', null, false)">
                        <td width="45px">
                        </td>
                        <td>
                            <img src="~/img/hd_disk_harddisk_162.png" style="height:45px;width:45px" />
                        </td>
                        <td>
                            <table>
                                <tr>
                                    <td>
                                        локальный диск (@driveInfo.Name.Replace("\\", ""))
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <progress value="@(driveInfo.TotalSize.ToGB(0) - driveInfo.TotalFreeSpace.ToGB(0))" max="@driveInfo.TotalSize.ToGB(0)"></progress>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @driveInfo.TotalFreeSpace.ToGB() ГБ свободно из @driveInfo.TotalSize.ToGB() ГБ
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</div>


<div id="FileBrowser" style="width:100%; height:auto">
    <div id="PanelPath" style="width:100%">
        <div id="PanelPathButtons">
            <button id="left" onclick="Back()"><img src="~/img/left.png" width="20px" height="10px" /></button>
            <button id="right" onclick="Next()"><img src="~/img/right.png" width="20px" height="10px" /></button>
        </div>
        <div id="PathNow">@WebFileManager.Controllers.FilesController.folderModels[0].ThisDirectoryInfo.FullName</div>
    </div>
    <div id="FileManager">

        <div id="PathView" class="FileManager" style="width:30%;">
            fff
        </div>
        <div id="FilesView" class="FileManager" style="width: 70%; ">
            <table id="FilesAndFolders">
                <tr>
                    <th onclick="Sort(this)" style="cursor: pointer"> Name </th>
                    <th onclick="Sort(this)" style="cursor: pointer">Change date</th>
                    <th onclick="Sort(this)" style="cursor: pointer"> Type </th>
                    <th onclick="Sort(this)" style="cursor: pointer"> Size </th>
                </tr>
                @{
                    foreach (var folder in WebFileManager.Controllers.FilesController.folderModels[0].Folders)
                    {
                        <tr class="FileFolderRow">
                            <td>
                                <img src="~/img/folder.png" /> @folder.ThisDirectoryInfo.Name
                            </td>
                            <td>
                                @folder.ThisDirectoryInfo.LastWriteTime
                            </td>
                            <td>
                                Folder
                            </td>
                            <td>
                                @folder.Size.ToMB() MB
                            </td>
                        </tr>
                    }
                    foreach (var file in WebFileManager.Controllers.FilesController.folderModels[0].Files)
                    {
                        <tr class="FileFolderRow">
                            <td>
                                <img src="~/img/file.png" />@file.Name
                            </td>
                            <td>
                                File
                            </td>
                            <td>
                                @file.Length.ToMB() MB
                            </td>
                        </tr>
                    }
                }
                <tr>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<script>
    $(dbClickRow())
    function VieUnvie() {
        var table = document.getElementById("allDisk");
        if (table.style.display == "none") {
            table.style.display = "block";
        }
        else {
            table.style.display = "none";
        }
    }

    function getFolder(FN, PN, Sor, BK) {
         $.ajax({
                    url: '@Url.Action("NewFolder", "Files")',
                    data:{
                        folderName: FN
                        , pathNow: PN
                        , orderBy: Sor
                        , back:BK
                }
                    , type: 'POST'
                    , success: function (data) {
                        $(".FileFolderRow").remove();
                        GetFileFolderRow(data);
                        pathNow: $('#PathNow')[0].innerText = data[0]["CurentPath"];
                        setSes("maxPath", data[0]["CurentPath"]);
                    }
                })
    }
    function dbClickRow () {
        $(".FileFolderRow").dblclick(function (e) {
            var newFolder = this.getElementsByTagName("td")[0].innerText.trim();
            if (this.getElementsByTagName("td")[2].innerText == "Folder") {
                getFolder(newFolder, $('#PathNow')[0].innerText, null, false)
            }
            else {
                alert("i can't open files ");
            }
        })

    }
    function GetFileFolderRow(data) {
        for (var i = 0; i < data.length; i++) {
            let tr = document.createElement("tr"),
                td0 = document.createElement("td"),
                td1 = document.createElement("td"),
                td2 = document.createElement("td"),
                td3 = document.createElement("td"),
                img = document.createElement("img");
            if (data[i]["Type"] == "File") { img.src = "/img/file.png" }
            else { img.src = "/img/folder.png" }
            td0.appendChild(img);
            td0.appendChild(document.createTextNode(data[i]["Name"]));
            td1.innerText = data[i]["ChangeDate"];
            td2.innerText = data[i]["Type"];
            td3.innerText = data[i]["Size"] + " MB";
            tr.className = "FileFolderRow";
            tr.append(td0);
            tr.append(td1);
            tr.append(td2);
            tr.append(td3);
            $("#FilesAndFolders").append(tr);
        }
        $(dbClickRow())
    }
    function Back() {
        @*$.ajax({
                    url: '@Url.Action("NewFolderBack", "Files")',
                    data:{
                        pathNow: $('#PathNow')[0].innerText
                }
                    , type: 'POST'
                    , success: function (data) {
                        $(".FileFolderRow").remove();
                        GetFileFolderRow(data);
                        pathNow: $('#PathNow')[0].innerText = data[0]["CurentPath"];
                    }
        })*@
        getFolder(null, $('#PathNow')[0].innerText, null, true);
        $("#right").prop("disabled", false)
    }
    function Next() {
        var maxPath = getSession("maxPath");
        if (maxPath == null) { return; }
        var path = $('#PathNow')[0].innerText;
        if (maxPath.lncludes(path) && maxPath != path) {
            var nextFolder = maxPath.substring(path.length + 1);
            nextFolder = nextFolder.substring(0, nextFolder.indexOf("\\"));
            $.ajax({
                url: '@Url.Action("NewFolderBack", "Files")',
                data: {
                    pathNow: path + nextFolder
                }
                    , type: 'POST'
                    , success: function (data) {
                        $(".FileFolderRow").remove();
                        GetFileFolderRow(data);
                        pathNow: $('#PathNow')[0].innerText = data[0]["CurentPath"];
                    }
        })
        }
        if (maxPath == path) { $("#right").prop("disabled", true); }
    }
    function getSession(nameSes) {
        var path;
        $.ajax({
            url: '@Url.Action("GetSessionValueByName", "Sessions")',
            async: !1,
                    data:{
                        name: nameSes
                }
                    , type: 'POST'
            , success: function (data) {
                path = data;
                return data;
                    }
        })
        return path;
    }
    function setSes(name, val) {
        $.ajax({
                    url: '@Url.Action("SetSessionValue", "Sessions")',
                    data:{
                        name: name,
                        value: val
                }
                    , type: 'POST'
                    , success: function (data) {
                    }
                })
    }
    function Sort(e) {
        @*setSes("SortBy", e.innerText);
        $.ajax({
                    url: '@Url.Action("NewFolderBack", "Files")',
                    data:{
                        pathNow: $('#PathNow')[0].innerText
                }
                    , type: 'POST'
                    , success: function (data) {
                        $(".FileFolderRow").remove();
                        GetFileFolderRow(data);
                        pathNow: $('#PathNow')[0].innerText = data[0]["CurentPath"];
                    }
        })*@
        getFolder(null, $('#PathNow')[0].innerText, e.innerText, false);
    }
    //function DiskRowClick(e) {
    //    getFolder(null, e.innerText, null, false)
    //}
</script>
<style>
    .FileManager {
        border: 4px solid;
        border-color: blueviolet;
        float: left
    }

    #FileManager {
        margin-top: 5px;
        height: 700 px;
    }

    .FileFolderRow:hover {
        background-color: aqua;
    }

    #PathView {
        float: left;
    }

    #PathNow {
        border: 1px solid;
        border-color: blueviolet;
        margin-left: 80px;
    }

    #PanelPathButtons {
        float: left;
    }

    #FilesView {
        overflow-y: scroll;
        padding: 20px;
        height: 760px;
        margin-bottom: 90px;
    }
    .FileFolderRow{
        cursor:default;
    }
</style>